module.exports = {
  getBrands: jest.fn(),
  addBrand: jest.fn(),
  deleteBrand: jest.fn(),
  getModelsByBrand: jest.fn(),
  addModel: jest.fn(),
  addBrands: jest.fn(),
  deleteBrands: jest.fn(),
  updateBrand: jest.fn(),
  searchBrand: jest.fn(),
  addModels: jest.fn(),
  deleteModels: jest.fn(),
  updateModel: jest.fn(),
  searchModel: jest.fn(),
  addYears: jest.fn(),
  deleteYears: jest.fn(),
  updateYear: jest.fn(),
  searchYear: jest.fn(),
};
